#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <stdint.h>

int main(int argc, char** argv)
{
	char buf[100000];
	int size = read(STDIN_FILENO, buf, 99999);

	char* p_buf = buf;
	int seq_len = 0;

	int reg[1000];
	int len[1000];
	int d[1000][8];

	while(p_buf = strstr(p_buf, "i2c w"))
	{
		p_buf += strlen("i2c w");
//		printf("%s", p_buf);
		int ret = sscanf(p_buf, "%x %x %x %x %x %x %x %x %x", &reg[seq_len], &d[seq_len][0],&d[seq_len][1],&d[seq_len][2],&d[seq_len][3],&d[seq_len][4],&d[seq_len][5],&d[seq_len][6],&d[seq_len][7]);
		if(ret < 1)
		{
			fprintf(stderr, "Error: scanf couldn't read register address.\n");
			return 1;
		}

		len[seq_len] = ret-1;

		seq_len++;
		if(seq_len >= 1000)
		{
			fprintf(stderr, "File too long\n");
			return 1;
		}

	}


	printf("/*\n");
	printf("\tEspros EPC635 Sequencer Program (i.e., Espros' firmware for EPC635 chip)\n");
	printf("\n");
	printf("\tI2C sequence within this program copyright Espros Photonics Corporation\n");
	printf("\n");
	printf("\tPulu Robotics Oy has Espros Photonics Corporations permission to share this program to Pulu's customers only.\n");
	printf("\tPublic sharing is probably not allowed.\n");
	printf("\n");
	printf("\tDo not redistribute.\n");
	printf("\n");
	printf("\tFILE AUTOGENERATED by epc_sequencer_converter.c . Do not modify by hand.\n");
	printf("*/\n");

	printf("#include <stdint.h>\n\n");
	printf("typedef struct {\n");
//	printf("\tuint8_t reg;\n");
	printf("\tuint8_t len;\n");
	printf("\tuint8_t d[9];\n");
	printf("} seq_elem_t;\n\n");

	printf("#define SEQ_LEN %d\n", seq_len);
	printf("seq_elem_t epc_seq[SEQ_LEN] = {\n");
	for(int i = 0; i < seq_len; i++)
	{
		printf("	{ %d, {0x%02x, ", len[i]+1, reg[i]);
		for(int o=0; o<8; o++)
		{
			printf("0x%02x", d[i][o]);
			if(o<7) printf(", ");
		}
		printf("} }");
		if(i<seq_len-1) printf(",\n"); else printf("\n");
	}

	printf("};\n");
	
	return 0;
	
}
