//AUTOGENERATED FOR Fled = 6666666.667
#ifndef TOF_TABLE_H
#define TOF_TABLE_H

#include <stdint.h>

#define TOF_TBL_LEN 256

#define TOF_TBL_PERIOD 22484

#define TOF_TBL_HALF_PERIOD 11242

#define TOF_TBL_QUART_PERIOD 5621

extern const int16_t tof_tbl[TOF_TBL_LEN] __attribute__((section(".tof_tbl")));

#endif
